In [56]:
import numpy as np

In [57]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [58]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [59]:
def evaluate_population( pop ):
    """
    Hàm đánh giá tất cả cá thể trong quần thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    values = np.array([onemax(ind) for ind in pop])     #lấy các giá trị của các cá thể ind trong quần thể pop
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return values

In [64]:
def evaluate_algorithm(num_individuals, num_parameters, num_generations):
  count = 0
  for i in range(30):
    np.random.seed(i)
    final_offspring = popop(num_individuals, num_parameters, num_generations)
    if num_parameters in final_offspring:
      count +=1

  return count

In [61]:
def tournament_selection( pop, pop_fitness, selection_size, tournament_size):
    """
    Hàm chọn lọc cạnh tranh.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)                              #pop: quần thể đang thực hiện phép chọn lọc
    indices = np.arange(num_individuals)
    selected_indices = []                                   #chỉ số của những cá thể được chọn
    
    while len(selected_indices) < selection_size:           # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể.
        np.random.shuffle(indices)                          #selection_size: số cá thể được chọn
        
        for i in range(0, num_individuals, tournament_size):#tournament_size: số cá thể cạnh tranh với nhau mỗi lần so sánh
          best_idx = i
          for idx in range(1, tournament_size):
            if better_fitness(pop_fitness[indices[i+idx]], pop_fitness[indices[best_idx]]):     #so sánh các cá thể 
              best_idx = i + idx
          selected_indices.append(indices[best_idx])
    
    selected_indices = np.array(selected_indices)           #trả về chỉ số của những cá thể được chọn 

    ### DỪNG CODE TẠI ĐÂY ###
    
    return selected_indices

In [60]:
def better_fitness( fitness1, fitness2, maximization=True ):
    """
    Hàm so sánh độ thích nghi của 2 cá thể.
    """
    
    if maximization:                            #Nếu bài toán đang thuộc dạng tối đa hóa
        if fitness1 > fitness2:               #Return true nếu fitness1 > fitness 2 và ngược lại
            return True
    else:
        if fitness1 < fitness2:
            return True
        
    return False

In [62]:
def variation( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.arange(num_individuals)
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        #Uniform crossover
        for idx in range(0, num_parameters):
          r = np.random.rand()
          if r < 0.5:
            temp = offspring2[idx]
            offspring2[idx] = offspring1[idx]
            offspring1[idx] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [63]:
def popop(num_individuals, num_parameters, num_generations):
    """
    Cài đặt POPOP
    
    Arguments:
    num_individuals -- Số lượng cá thể trong quần thể.
    num_parameters -- Số lượng biến.
    num_generations -- Số thế hệ thuật toán sẽ chạy.

    Returns:
    In ra quần thể ở thế hệ cuối cùng và giá trị của từng cá thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    # Khởi tạo quần thể
    pop = initialize_population(num_individuals, num_parameters)
    pop_fitness = evaluate_population(pop)
    print("Gen 0:")
    print(pop)
    print(pop_fitness)
    
    selection_size = len(pop)
    tournament_size = 4

    for i in range(num_generations):            # Tạo ra các cá thể con và đánh giá chúng
        offspring = variation(pop)
        offspring_fitness = evaluate_population(offspring)
        
        mix = np.vstack((pop,offspring))        #tạo mix gồm pop và offspring
        mix_fitness = np.hstack((pop_fitness, offspring_fitness))
 
        mix_indices = tournament_selection(mix, mix_fitness, selection_size, tournament_size)     #tournament selection

        pop = mix[mix_indices, :]     #thay thế quần thể cũ bằng quần thể mới
        pop_fitness = mix_fitness[mix_indices]
        print("Gen {}:".format(i+1))
        print(pop_fitness)

    ### DỪNG CODE TẠI ĐÂY ###
    print("Result:")
    print(pop)
    print(pop_fitness)

    return pop_fitness

In [65]:
# Trường hợp kích thước quần thể là 8
np.random.seed(20521394)
num_parameters = 16
num_individuals = 8
num_generations = 8
popop(num_individuals, num_parameters, num_generations)

Gen 0:
[[1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 0]
 [0 0 1 1 0 1 1 0 1 1 0 0 0 0 1 0]
 [1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 1 1 0 1 0 1 0 0 1 0 1 0 1 1 1]
 [0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 0 1 0 0 0 1 0 1 0]
 [0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1]]
[ 9  7  5 10  9  5  9  9]
Gen 1:
[ 9  9 10 10 10  9 10  9]
Gen 2:
[11 10 10 10 11 10 10 10]
Gen 3:
[13 11 10 11 10 11 11 13]
Gen 4:
[11 13 12 13 13 13 13 12]
Gen 5:
[13 13 13 13 13 13 13 13]
Gen 6:
[13 13 13 13 13 13 13 13]
Gen 7:
[13 14 13 13 13 13 13 14]
Gen 8:
[14 13 14 14 14 14 14 14]
Gen 9:
[14 14 14 14 14 14 14 14]
Gen 10:
[14 14 14 14 14 14 14 14]
Result:
[[1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1]]
[14 14 14 14 14 14 14 14]


array([14, 14, 14, 14, 14, 14, 14, 14])

In [66]:
# Trường hợp kích thước quần thể là 16
np.random.seed(20521394)
num_parameters = 24
num_individuals = 16
num_generations = 16
popop(num_individuals, num_parameters, num_generations)

Gen 0:
[[1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 1 0]
 [1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 1 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0 1 0 1]
 [0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0]
 [1 0 0 0 1 1 1 1 1 1 1 0 1 0 0 1 1 0 1 1 1 0 1 1]
 [0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 1 0 0 1]
 [1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1]
 [1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 1 0 0]
 [0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 1]
 [0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0]
 [1 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 0 1]
 [0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1]
 [0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0]]
[13  8 13 11 13 16 11 14 11 11  9 10 10 11 15 12]
Gen 1:
[13 15 16 13 17 13 15 15 15 15 15 13 13 13 16 17]
Gen 2:
[17 15 18 18 15 17 17 15 16 18 17 17 16 15 17 15]
Gen 3:
[17 1

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24])

In [67]:
# Trường hợp kích thước quần thể là 16
np.random.seed(20521394)
num_parameters = 32
num_individuals = 32
num_generations = 16
popop(num_individuals, num_parameters, num_generations)

Gen 0:
[[1 1 1 ... 0 1 0]
 [1 1 0 ... 1 1 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 1 ... 1 0 0]
 [0 1 1 ... 1 0 1]
 [1 1 1 ... 0 1 1]]
[16 15 14 18 18 18 13 15 13 13 18 17 14 13 16 18 16 22 15 14 18 15 14 12
 16 13 14 13 15 12 20 17]
Gen 1:
[17 22 18 20 18 16 21 18 18 17 17 17 22 16 18 18 18 18 21 17 18 17 16 16
 22 20 15 18 18 17 18 22]
Gen 2:
[20 22 22 20 18 22 18 18 21 22 22 18 19 20 22 22 21 21 22 22 20 22 20 20
 22 18 22 20 22 20 20 18]
Gen 3:
[22 21 22 23 23 23 22 22 22 24 20 22 23 22 24 22 22 22 23 22 22 22 24 22
 23 22 20 22 22 23 21 24]
Gen 4:
[23 24 25 23 23 24 24 24 24 23 22 24 24 23 25 23 24 23 22 22 23 24 24 25
 23 24 24 23 23 24 24 25]
Gen 5:
[24 25 26 25 24 27 25 25 25 25 24 27 25 26 28 26 24 25 23 24 25 23 28 26
 26 24 27 27 25 25 22 25]
Gen 6:
[26 28 27 28 26 27 25 27 25 29 26 26 25 26 27 28 28 27 25 27 27 28 28 29
 25 25 26 28 27 26 26 26]
Gen 7:
[28 28 30 30 28 27 27 29 28 28 26 27 29 30 28 29 28 27 28 29 29 30 28 27
 28 28 27 30 29 27 26 28]
Gen 8:
[29 30 30 29 28 30 30 29 

array([32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

In [68]:
# Trường hợp kích thước quần thể là 64
np.random.seed(20521394)
num_parameters = 48
num_individuals = 64
num_generations = 16
popop(num_individuals, num_parameters, num_generations)

Gen 0:
[[1 1 1 ... 0 0 1]
 [1 1 1 ... 0 1 0]
 [1 1 1 ... 0 1 1]
 ...
 [1 0 1 ... 1 1 0]
 [1 1 0 ... 1 0 1]
 [0 0 1 ... 1 0 0]]
[21 24 29 25 22 19 21 27 19 24 25 31 21 26 21 20 23 20 20 20 29 24 28 22
 26 22 22 21 23 32 22 22 25 25 24 21 24 28 18 30 28 27 31 20 25 26 28 26
 20 21 12 24 26 25 24 19 23 25 23 23 26 22 24 29]
Gen 1:
[26 24 24 32 29 24 28 31 30 29 31 31 28 28 26 30 32 24 29 28 25 28 26 28
 23 30 28 26 25 24 29 31 25 28 25 28 26 28 28 31 27 32 25 29 26 25 31 26
 29 30 25 26 32 27 27 31 30 29 24 26 29 26 31 30]
Gen 2:
[34 32 28 30 28 31 27 31 33 30 30 34 29 32 30 29 32 31 31 31 30 30 30 28
 30 32 32 29 34 32 31 32 34 31 33 30 34 32 31 32 31 30 31 31 29 31 30 29
 30 31 31 31 32 32 31 31 31 34 28 32 32 29 32 29]
Gen 3:
[33 32 34 31 38 36 31 34 32 31 33 34 34 32 31 34 31 35 32 34 33 33 32 34
 32 31 34 32 31 34 35 34 31 31 32 31 32 33 34 34 33 34 35 33 30 32 31 32
 35 34 32 34 34 34 32 34 31 32 31 31 38 33 36 34]
Gen 4:
[34 37 35 36 37 33 32 34 36 35 35 34 35 35 34 36 35 35 34 34 

array([48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48])

In [69]:
# Trường hợp kích thước quần thể là 128
np.random.seed(20521394)
num_parameters = 64
num_individuals = 128
num_generations = 20
popop(num_individuals, num_parameters, num_generations)

Gen 0:
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 0 ... 0 0 0]
 [0 1 1 ... 1 0 1]
 [0 0 0 ... 1 0 0]]
[31 32 36 28 26 35 27 34 38 29 33 26 29 27 27 37 34 32 35 30 26 33 37 29
 35 32 28 33 30 37 37 40 29 36 32 37 27 22 28 35 32 27 31 34 29 34 29 38
 33 38 32 34 30 24 33 20 31 35 35 27 29 35 33 34 32 29 33 31 35 27 31 33
 30 28 31 37 33 29 39 32 30 32 30 36 31 32 34 29 31 35 33 28 34 33 34 32
 44 33 37 36 33 23 36 28 29 32 34 36 31 34 29 41 21 33 32 34 33 39 35 37
 34 30 38 35 37 33 39 37]
Gen 1:
[35 37 27 33 35 34 36 38 38 39 32 34 30 38 36 39 39 37 35 33 37 39 36 36
 33 36 38 36 37 32 29 38 34 36 33 39 39 33 37 37 39 35 34 33 34 37 42 36
 44 38 37 35 38 37 37 38 39 33 35 40 41 35 36 35 41 36 34 35 37 36 35 37
 36 39 33 35 39 30 36 38 38 37 39 32 42 36 37 37 39 39 30 38 35 35 37 35
 38 34 33 37 39 37 33 33 35 32 37 33 39 37 33 39 35 39 38 40 34 36 33 44
 34 36 34 35 37 36 31 34]
Gen 2:
[40 44 38 39 43 38 39 37 39 40 36 37 38 44 37 39 39 39 37 37 40 36 37 37
 39 

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64])

In [71]:
#  Khi problem size càng lớn thì nums_generation phải càng lớn theo
#  Một problem size có một giá trị fitness cho các cá thể tối đa, nên khi đã đạt giá trị đó thì dù tăng thêm nums_generation
#  thì giá trị vẫn không tăng lên
#  Với đa số các trường hợp chạy trong bài thì nums_generation cần để đạt giá trị fitness tối đa đều dưới 20